#!/bin/sh

# create riak group only if it doesn't already exist
getent group riak >/dev/null 2>&1
if [ $? -ne 0 ]; then
        groupadd riak
fi

# create riak user only if it doesn't already exist
getent passwd riak >/dev/null 2>&1
if [ $? -ne 0 ]; then
        useradd -g riak -d /opt/riak riak
        usermod -c "Riak Server" riak
fi

