
##
## Export all variables to sub-invocation
##
export

bootstrap:
	$(REBAR) -v create \
                    template_dir=$(PKG_ID)/$(DEPS_DIR)/node_package/priv/templates \
                    template_vars=$(PKG_ID)/pkg.vars.config template=rpm
	make -f Makefile
