
##
## Export all variables to sub-invocation
##
export

bootstrap:
	mkdir -p $(PKG_ID)/debian
	cd $(PKG_ID)/debian && $(REBAR) -v create \
                              template_dir=../$(DEPS_DIR)/node_package/priv/templates \
                              template_vars=../pkg.vars.config template=deb
	make -C $(PKG_ID) -f debian/Makefile
