#! /bin/sh
#
# gen_dev dev4 vars.src vars
#
# Generate an overlay config for devNNN from vars.src and write to vars
#

NAME=$1
TEMPLATE=$2
VARFILE=$3

## Allocate 10 ports per node
##   .
##   .7 - http
NODE="$NAME@127.0.0.1"

NUMBER=${NAME##dev}
BASE=$((10000 + 10 * $NUMBER))
PBPORT=$(($BASE + 7))
WEBPORT=$(($BASE + 8))
HANDOFFPORT=$(($BASE + 9))

echo "Generating $NAME - node='$NODE' pbc=$PBPORT http=$WEBPORT handoff=$HANDOFFPORT"
sed -e "s/@NODE@/$NODE/" \
    -e "s/@PBPORT@/$PBPORT/" \
    -e "s/@WEBPORT@/$WEBPORT/" \
    -e "s/@HANDOFFPORT@/$HANDOFFPORT/" < $TEMPLATE > $VARFILE
