#!/bin/sh

if [ "$2" != "POST-DEINSTALL" ]; then
    exit 0
fi

USER=riak

if getent group "${USER}" 2>/dev/null 1>&2; then
    echo "To delete ${USER} group permanently, use 'groupdel ${USER}'"
fi

if getent passwd "${USER}" 2>/dev/null 1>&2; then
        echo "To delete ${USER} user permanently, use 'userdel ${USER}'"
fi

exit 0