#!/bin/sh

USER=riak
RIAK_DATA_DIR=/var/db/riak
RIAK_LOG_DIR=/var/log/riak
RIAK_BIN_DIR=/opt/local/sbin

if [ "$2" = "PRE-INSTALL" ]; then
    if ! getent group "${USER}" 2>/dev/null 1>&2; then
        groupadd ${USER}
    fi

    if ! getent passwd "${USER}" 2>/dev/null 1>&2; then
        useradd -g ${USER} -d /opt/local/lib/${USER} -s /bin/sh ${USER}
    fi

    # Create var directories outside of +CONTENTS
    mkdir -p ${RIAK_DATA_DIR}
    chown -R ${USER}:${USER} ${RIAK_DATA_DIR}
    chmod 700 ${RIAK_DATA_DIR}
    mkdir -p ${RIAK_LOG_DIR}
    chmod 700 ${RIAK_LOG_DIR}
    chown -R ${USER}:${USER} ${RIAK_LOG_DIR}

fi

if [ "$2" = "POST-INSTALL" ]; then

    # Ensure proper permissions on riak scripts
    for i in riak riak-admin search-cmd; do
        chown ${USER}:${USER} ${RIAK_BIN_DIR}/$i
        chmod 755 ${RIAK_BIN_DIR}/$i
    done

    # Create Riak project
    if ! projects -l riak >/dev/null 2>&1; then
        projadd -U riak -G riak \
        -K "process.max-file-descriptor=(priv,262140,deny)" \
        -c "Riak default project" riak
    fi

    # Import SMF definitions
    svccfg import /opt/local/share/smf/riak-epmd/manifest.xml
    chmod 755 /opt/local/share/smf/riak-epmd/riak-epmd
    svccfg import /opt/local/share/smf/riak/manifest.xml
fi

exit 0
