#!/bin/sh

if [ "$2" != "POST-DEINSTALL" ]; then
    exit 0
fi

USER=riak

if pw usershow "${USER}" 2>/dev/null 1>&2; then
        echo "To delete riak user permanently, use 'pw userdel ${USER}'"
fi

exit 0
