#!/bin/sh

if [ "$2" != "PRE-INSTALL" ]; then
    exit 0
fi

if ! pw groupshow riak >/dev/null; then
	if pw groupadd riak; then
		echo "Added group riak"
	else
		echo "Failed to add group riak" >&2
		exit 1
	fi
fi

if ! pw usershow riak >/dev/null; then
	if pw useradd riak -g riak -h - -d /usr/local/riak -s bash -c "RIak Server"; then
		echo "Added user riak"
	else
		echo "Failed to add user riak" >&2
		exit 1
	fi
fi

#eof