#!/bin/bash

RUNNER_GEN_DIR={{platform_gen_dir}}
RELX_RIAK={{platform_bin_dir}}/riak
export PID_DIR={{pid_dir}}

mkdir -p $PID_DIR $PIPE_DIR

case "$1" in
    start)
        $RELX_RIAK $* -pa {{platform_patch_dir}}
        test -r $PID_DIR/riak.pid && exit 0
        ;;
    console|foreground)
        $RELX_RIAK $* -pa {{platform_patch_dir}}
        ;;
    stop)
        $RELX_RIAK $* \
            && rm -f $PID_DIR/riak.pid
        ;;
    *)
        ESCAPED_ARGS=`echo "$@" | sed -e 's/\([\\\(\\\){}"\x27]\)/\\\\\1/g'`
        $RELX_RIAK $ESCAPED_ARGS
        ;;
esac
