#!/usr/bin/env escript
%% -*- erlang -*-

main([ConfigPath]) ->
    try
        {ok, _} = file:consult(ConfigPath),
        io:format("config is OK\n")
    catch
        _:_ ->
            io:format("Error reading ~p\n", [ConfigPath])
    end.
