#!/bin/sh
# -*- tab-width:4;indent-tabs-mode:nil -*-
# ex: ts=4 sw=4 et

## cf_config defines the config arguments needed
. bin/cf_config

## "vm.args = $VMARGS_PATH"
## "app.config = $CONFIG_PATH"

CODE=" try
           {ok, _} = file:consult(\"$CONFIG_PATH\"),
           io:format(\"config is OK\\n\"),
           halt(0)
       catch
           _:_ ->
               io:format(\"Error reading ~p\\n\", [\"$CONFIG_PATH\"]),
               halt(1)
       end."

$BINDIR/erl -noshell -boot start_clean -eval "$CODE"

echo $CUTTLE_CONF

# No explicit exit, assumed to have succeeded
exit 0
