#!/bin/sh
# -*- tab-width:4;indent-tabs-mode:nil -*-
# ex: ts=4 sw=4 et

SUPPRESS_HYPH_DEPREC_WARN={{suppress_hyphen_deprec_warning}}
if [ x$1 = x"--suppress-deprecation-warning" ]; then
    shift
elif [ x${SUPPRESS_HYPH_DEPREC_WARN} != x"yes" ]; then
    echo "The hyphenated form of this command is deprecated. \
Please fix your scripts to call \`riak chkconfig\` instead.
"
fi

PLATFORM_BASE_DIR={{platform_base_dir}}
PLATFORM_BASE_DIR=${PLATFORM_BASE_DIR:-$(cd $(dirname "$0")/.. && pwd -P)}
RPC_HOP="${PLATFORM_BASE_DIR}/bin/riak rpc"
RPCt_HOP="${PLATFORM_BASE_DIR}/bin/riak rpcterms"

ERTS_VER=$(cd ${PLATFORM_BASE_DIR} && ls -d erts-*)
ERTS_PATH="${PLATFORM_BASE_DIR}/$ERTS_VER/bin"

PLATFORM_ETC_DIR={{platform_etc_dir}}
if [ "$PLATFORM_ETC_DIR" = "${PLATFORM_ETC_DIR#/}" ]; then
    PLATFORM_ETC_DIR=$PLATFORM_BASE_DIR/$PLATFORM_ETC_DIR
fi

COOKIE=`egrep '^[ \t]*distributed_cookie[ \t]*=[ \t]*' "$PLATFORM_ETC_DIR"/riak.conf 2> /dev/null | cut -d = -f 2 | tr -d ' '`
NODE={{node}}
HOST=${NODE#*@}

BOOT_FILE="${PLATFORM_BASE_DIR}/releases/{{release_version}}/start_clean"

PLATFORM_GEN_DIR={{platform_gen_dir}}
if [ "$PLATFORM_GEN_DIR" = "${PLATFORM_GEN_DIR#/}" ]; then
    PLATFORM_GEN_DIR=$PLATFORM_BASE_DIR/$PLATFORM_GEN_DIR
fi

CONFIG_PATH=`ls -1r ${PLATFORM_GEN_DIR}/generated.conf/app.*.config | head -n1`
VMARGS_PATH=`ls -1r ${PLATFORM_GEN_DIR}/generated.conf/vm.*.args | head -n1`

CODE=" try
           {ok, _} = file:consult(\"$CONFIG_PATH\"),
           io:format(\"config is OK\\n\"),
           halt(0)
       catch
           _:_ ->
               io:format(\"Error reading ~p\\n\", [\"$CONFIG_PATH\"]),
               halt(1)
       end."

$ERTS_PATH/erl -noshell -noinput \
               -pa $PLATFORM_PATCH_DIR \
               -boot $BOOT_FILE \
               -hidden -name riak_chkconfig$RAND@$HOST -setcookie $COOKIE \
               -node $NODE  -tracing off \
               -eval "$CODE"

echo $CONFIG_PATH $VMARGS_PATH
